//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBookTrading.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=filesandfoldersstorage;AccountKey=ZMCU" +
            "CB7Q933eTv9TwM2CFIKsiO8ccBjMaK4ZXV4FDA0tqaW0rhAdC1LykrZR9SR09xZ7lJmc6cAcHanU7+CI" +
            "uw==;EndpointSuffix=core.windows.net")]
        public string cloudStorageString {
            get {
                return ((string)(this["cloudStorageString"]));
            }
            set {
                this["cloudStorageString"] = value;
            }
        }
    }
}
